### ISSUE TITLE
Logic level shifting breakout cannot mount SD card - mount error 3

### ISSUE THREAD

**Issue by matt-walker0** [elehobica/pico_fatfs#7]
Hello,

Firstly many thanks for developing the library.
I seem to have found an issue to get the SD card to mount without error. I'd assumed this was due to my poor wiring or pin selection. However having tried an alternate [pico-fatfs](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/tree/196016f525e5b9c161f2b965ddd3045a4ef87649/simple_example) library this works without issue, writing `Hello World` to the SD card (viewable on another device). This is currently setup on a breadboard with a mess of wires, so expect poor signaling but attempting to lower CLK_FAST to as low as 1 MHZ has not helped. I've tried switch SPI lanes and pins to no avail either. The SD card reader used is [this](https://lastminuteengineers.com/arduino-micro-sd-card-module-tutorial/) and is hooked up-to the 5v rail for power.

Any ideas how to debug a `mount error 3`?

_Doubt it would change anything, but I've set the example code `test/main.cpp` to use USB serial out for debugging._

**Comment by elehobica** [comment]
Hello @matt-walker0 

Thank you for the issue report.
According to your explanation, you're using the microsd board with level-shifter.
If I'm correct, generally, the board with level-shifter should be used with 5V-TTL level I/O interface board such as Arduino UNO to interface between 5V (MCU side) and 3.3V (microsd card side).
On the other hand, rp2040 (Raspberry Pi Pico board) handles directly 3.3V LVTTL, the board without level-shifter like [this](https://www.smart-prototyping.com/Micro-SD-card-reader-breakout-board) needs to be used.
I've never make it work with the board with level-shifter even though 3.3V is connect for both side of the voltage inputs. I think that is exactly same as what you saw. In that case, to decrease clock frequency doesn't improve the situation at all. Therefore, my first recommendation is to replace the microsd board.

On the other hand, I also appreciate your information that the other library runs successfully even with the board with level-shifter. That could indicates it has more timing margin than this library. It looks worth investigating what makes difference.

At last, but not least, I'd appreciate if you kindly inform which vendor's microsd card you're using. (vendor, series name and size).

BR

**Comment by elehobica** [comment]
Thanks @matt-walker0 for the card information.
I'll try again the board with level-shifter to check if any condition to work.
Best Regards

**Comment by elehobica** [comment]
Thank you for the trial and the report with non-level-shifter board.
Yes, for the moment in this library, it should be understood that level shifter makes negative effect on the timing for SPI interface to microsd
Without level shifter, sometimes still speed down should be needed.
Please note that the frequency is not applied in linear but applied as frequency that doesn't exceed to 125MHz/N.
If it is set to 50MHz, then actual frequency is 31.25MHz and if it's set to 30MHz, actual frequency will get 15.625MHz.

Best Regards

**Comment by fhoedemakers** [comment]
Hi,

I think my issue is related to this issue and i hope you can help me.

I'm the author of the PicoNes NES emulator ( https://github.com/fhoedemakers/pico-infonesPlus ). The emulator supports different RP2040/RP2450 board variants and SDcard breakout board types.
I used the same older SDcard driver as mentioned at the beginning of this issue. https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico 
All my configurations  work fine with this older driver.
I was recently asked to make the emulator run on a new type of board:  [Adafruit Metro RP2350](https://www.adafruit.com/product/6267) 
For this board  I could not get the sdcard to work using this older driver. In stead i decided to use your version, on which the sdcard just works fine for this board. 
All my other configs also work fine except for the [Pimoroni Pico DV demo base](https://shop.pimoroni.com/products/pimoroni-pico-dv-demo-base?variant=39494203998291)
Mounting the SDcard always results in error 3.

You can find the datasheet of the board [here](https://cdn.shopify.com/s/files/1/0174/1800/files/pico_dv_schematic.pdf?v=1636985340)

Is there a way to solve this or do you have any suggestions? I cannot not use another sdcard board, since de sdcard slot is attached to the pcb.

For now i decided to use the old SDcard driver for the Pimoroni Board and your implementation for all the other configurations. This however is not an ideal situation.

Below the test program config for the Pimoroni Pico DV:

````C
    printf("=====================\n");
    printf("== pico_fatfs_test ==\n");
    printf("=====================\n");

    // modify below if customized configuration is needed
    pico_fatfs_spi_config_t config = {
        spi0,
        CLK_SLOW_DEFAULT,
        CLK_FAST_DEFAULT,
        19,  // MISO
        22,  // CS
        5,  // sck
        18,  // MOSI
        true  // use internal pullup
    };
````

![Image](https://github.com/user-attachments/assets/c8a17e1d-d9a6-4f9d-8440-92a6b5c17f52)

This SDcard implementaion is not public yet. You can find it in these branches

- https://github.com/fhoedemakers/pico-infonesPlus/tree/fruitjam (emulator)
- https://github.com/fhoedemakers/pico_shared/tree/fruitjam ( This is a submodule used by the emulator)

**Comment by elehobica** [comment]
Hi @fhoedemakers 

Thank you for the adoption trial of your project. I also appreciate the precise report about the issue, therefore I can reply to you with the analysis through the test.
I have saw the schematic of [Pimoroni Pico DV demo base](https://shop.pimoroni.com/products/pimoroni-pico-dv-demo-base?variant=39494203998291) board.
Honestly it looks to me quite it has bad manner pin assignment for microsd.
In general, if SD card interface is used with SPI interface of Raspberry Pi Pico, the pins needs to be correctly chosen from proper SPI function pins. On the other hand, the pin assignment of the board doesn't follow the manner. Please take a look at below image for the pin assignment situation in the Pimoroni board.

![Image](https://github.com/user-attachments/assets/05cb0273-639f-475e-bee6-8022e0302bd4)

The pins are selected from SPI0_x category, however, the roles of the pin are not matched. I think that's why it doesn't work with this repository. I have tested with the exact pin assign in the breadboard, I got completely the same result.

But at the same time, I wonder why it works on  https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico repository according to your report. If it's not SPI master function, bit-banging SPI or dedicated SPI implementation with Pico PIO could make it, however, it seems not likely.

**Comment by fhoedemakers** [comment]
Hi @elehobica,

Thanks for looking into the issue. The https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico repository I’m using relies on PIO, which might explain why it works with this setup.

For this particular board, I’ll continue using the carlk3 repository. For all other configurations, I’ll use your repository.

Yesterday, I also got mount error 3 in one specific configuration — the [Adafruit Metro RP2350](https://www.adafruit.com/product/6267)— when compiled for RISC-V. When compiled for ARM, the board works just fine.  
I still need to investigate this further, but since it works for ARM, it’s not a problem for me. I’ll just exclude the RISC-V binary from the release.

Best regards,

Frank

**Comment by elehobica** [comment]
Thanks for your reply.
If you're using https://github.com/carlk3/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico, not https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico, then I'll understand. I still found no clue if the latter is working on PIO. 

Best Regards

**Comment by elehobica** [comment]
@fhoedemakers  ah, I understand the situation from https://github.com/fhoedemakers/pico_shared/tree/fruitjam/drivers/pio_fatfs/sdcard . PIO is not SDIO but SPI master interface is implemented on PIO. It should work. This looks good idea to support flexible pin assignment in spite of using SPI master interface.

**Comment by fhoedemakers** [comment]
@elehobica

> [@fhoedemakers](https://github.com/fhoedemakers) ah, I understand the situation from https://github.com/fhoedemakers/pico_shared/tree/fruitjam/drivers/pio_fatfs/sdcard . PIO is not SDIO but SPI master interface is implemented on PIO. It should work. This looks good idea to support flexible pin assignment in spite of using SPI master interface. I'll try to introduce it that function when I have a time.

Sorry for the confusion.


> I'll try to introduce it that function when I have a time.

Thanks, that would be great!

**Comment by elehobica** [comment]
[Pimoroni Pico DV demo base](https://shop.pimoroni.com/products/pimoroni-pico-dv-demo-base?variant=39494203998291) board issue is not related to level-shifter issue, therefore, I've created [new issue](https://github.com/elehobica/pico_fatfs/issues/8) to cope with it.
